apiVersion: v1
appVersion: v1.0.0
description: Authenticator for using Dex with Kubernetes
maintainers:
- email: aaron@roydhouse.com
  name: Aaron Roydhouse
- email: nbadger@mintel.com
  name: Nick Badger
name: dex-k8s-authenticator
sources:
- https://github.com/mintel/dex-k8s-authenticator
version: 1.0.0
