dependencies:
- name: redis
  version: 1.1.19
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: db2
  version: 0.4.2
  repository: file://../db2
  condition: db2.enabled
