# Default values for perry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: cwds/perry
  tag: 4.0.0_993-RC
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  clientPort: 443
  adminPort: 9082

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 2048Mi
    cpu: 2000m

nodeSelector: {}

tolerations: []

affinity: {}

###
### Perry configuration
###
db:
  cms:
    database: DBN1SOC
    user: CWDSNS3
    url: jdbc:db2://db-1a.nonprod-gateway.cwds.io:4016/DBN1SOC
    schema: CWSNS1

token:
  timeout: 480
  name: access_token
  store:
    url: jdbc:postgresql://postgresql.sandboxk8.cwds.io:5432/sandboxk8?currentSchema=perry
    user: sandboxk8_postgres
    schema: perry

idp:
  base_url: https://sandboxk8cwds.auth.us-west-2.amazoncognito.com
  client_id: g9p2rvtlttf1alf4cga9dsv8t
  mapping_script: config/cognito.groovy
  auth_schema: query
  client_auth_schema: header
  validate_interval: 60
  host: cognito-idp.us-west-2.amazonaws.com
  enabled: true
  iam_access_id: AKIAI4PLOEK52ZUPANHA
  aws_region: us-west-2
  userpool: us-west-2_8u1FAcwMx

idm:
  enabled: true
  mapping_script: config/idm.groovy
  basic_auth_user: idmperry

sp:
 identity_mapping_script: config/default.groovy
 intake_identity_mapping_script: config/intake.groovy

swagger:
  enabled: true

environment:
  url: https://web.sandboxk8.cwds.io

##
## Redis chart configuration
##
redis:
  ## Whether to use redis or not. If disabled the application will be configured to run without redis.
  enabled: true
  port: 6379
  host: intake.redis.sandboxk8.cwds.io
  ## Application appears to fail to connect when a password is used - TODO: investigate this - for now AWS is not support auth on redis side.
  redisPassword:

# Full URL to Perry (TODO: make this dynamic using Route53 annotations).
perryURL: http://localhost

ignore_oauth2_state: true
use_current_uri: true

# Major application parameters
devMode: true
mfaMode: false
log_level: INFO

dora_url: https://doraapi.sandboxk8.cwds.io
whitelist: " http*://*.sandboxk8.cwds.io/** http*://*.sandboxk8.cwds.io:*/** /**/* **/* "

# Optional application parameters can be specified below:
#env:
#- name:
#  value: