apiVersion: v1
kind: Secret
metadata:
  name: {{ template "perry.fullname" . }}
  labels:
    app: {{ template "perry.name" . }}
    chart: {{ template "perry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if not .Values.db2.enabled }}
  password:  {{ .Values.externalDB2.password | b64enc | quote }}
  {{ end }}