apiVersion: v1
kind: Secret
metadata:
  name: {{ template "perry.fullname" . }}
  labels:
    app: {{ template "perry.name" . }}
    chart: {{ template "perry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  db_cms_password: {{ .Values.db.cms.password | quote }}
  token_store_password: {{ .Values.token.store.password | quote }}
  saf-client-secret: {{ .Values.idp.client_secret | quote }}
  cognito-iam-secret: {{ .Values.idp.iam_secret | quote }}
  idm-basic-auth-password: {{ .Values.idm.basic_auth_password | quote }}