apiVersion: v1
kind: Service
metadata:
  name: {{ template "perry.fullname" . }}
  labels:
    app: {{ template "perry.name" . }}
    chart: {{ template "perry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: http-client
      protocol: TCP
      name: http-client
    - port: {{ .Values.service.adminPort }}
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  selector:
    app: {{ template "perry.name" . }}
    release: {{ .Release.Name }}
