apiVersion: v1
kind: Service
metadata:
  name: {{ template "perry.fullname" . }}
  namespace: {{ .Values.environment.name.split(".")[0] | lower }}
  labels:
    app: {{ template "perry.name" . }}
    chart: {{ template "perry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment.name.split(".")[0] | lower }}
  annotations:
    dns.alpha.kubernetes.io/internal: {{ template "perry.name" . }}.{{ .Values.environment.name }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:142152461930:certificate/821fb02e-7d1b-452e-8cf6-a5c8343d0c95
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: {{ .Values.service.clientPort | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: http-client
      protocol: TCP
      name: http-client
    - port: {{ .Values.service.adminPort }}
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  selector:
    app: {{ template "perry.name" . }}
    release: {{ .Release.Name }}
