apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "db2.fullname" . }}
  labels:
    app: {{ template "db2.name" . }}
    chart: {{ template "db2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "db2.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "db2.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecretName }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB2INST1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "db2.fullname" . }}
                  key: password
            - name: LICENSE
              value: "accept"
          ports:
            - name: db2
              containerPort: 50000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 50000
          readinessProbe:
            tcpSocket:
              port: 50000
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
