apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db2.fullname" . }}
  labels:
    app: {{ template "db2.name" . }}
    chart: {{ template "db2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if .Values.password }}
  password:  {{ .Values.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}