apiVersion: v1
kind: Service
metadata:
  name: {{ template "db2.fullname" . }}
  labels:
    app: {{ template "db2.name" . }}
    chart: {{ template "db2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50000
      protocol: TCP
      name: db2
  selector:
    app: {{ template "db2.name" . }}
    release: {{ .Release.Name }}
